name: CI

on: [push]

env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_IO }}

jobs:

# ----------------------------------------------
  unit-tests:
    runs-on: ubuntu-latest
    container: golang:1.13
    steps:

    - name: Git checkout
    # Fetches and pull the reporisory with correct branch
    # link: https://github.com/actions/checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Unit tests
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Code coverage report
      run: curl -s https://codecov.io/bash | bash

